### ISSUE TITLE
Tags (keywords/labels) everywhere (META ISSUE)

### ISSUE THREAD

**Issue by philippejadin** [philippejadin/agorakit#15]
Use a taggable package : https://github.com/cviebrock/eloquent-taggable 

- [x] search by tags
- [ ] popular tags this week for encoding
- [ ] autotag on file upload
- [x] simply use the edit form of ressource to add tagging feature
- [x] convert folders (in file module) to tags as a one time conversion process (artisan command)

- [x] Tags on files
- [x] Tags on groups
- [x] Tags on discussions
- [x] Tags on users

**Comment by danielsum** [comment]
Je mets en suspend celui là car il faut une interface et je préfèrerait utiliser Sass et Bower pour ça...

Le package est installé : + j'ai déjà configuré le model File pour l'example de comment l'intégrer : https://github.com/DraperStudio/Laravel-Taggable
